# [START cloudbuild]
steps:

# Clone environment Kubernetes definition
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/marcusrodmag/htmrt-backend.git', 'master']

  # This step runs the unit tests on the app
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install --trusted-host pypi.python.org -r src/requirements.txt && python src/test.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/htmrt-backend:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/htmrt-backend:$SHORT_SHA'
# [END cloudbuild]
