# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: python-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmrt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmrt-backend
  template:
    metadata:
      labels:
        app: htmrt-backend
    spec:
      containers:
      - name: server
        image: gcr.io/marcusrodmag/htmrt-backend
        ports:
        - containerPort: 8080
        env:
        - name: RUN_PORT
          value: "8080"
        - name: FLASK_DEBUG
          value: 'True'
        - name: ENV_NAME
          value: 'PROD'